$base='C:\Users\pc\Desktop\TheBlackLilyBloomsinHerEyes\chinese-patch\source\data\scenario\zh-CN\rogueLike\event'
$maps=@{}
$maps['6']=@{22='继续前进后，我来到一座从未见过的神社。[p]';23='看着深夜里被灯光照得明亮的赛钱箱，不知为何，我被一股强烈的祈祷冲动驱使。[p]';25='[emb exp="f.battleDataDic[''player''][''name'']"]消耗了[emb exp="f.consumeFragment"]个魔力碎片，向神社献上祈祷。[p]';26='究竟会发生什么……[p]';44='在神社的庇佑下获得了『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';58='在神社的庇佑下获得了『[emb exp="sf.itemConstList[f.getItemId][''name'']"]』道具！[p]';60='        道具持有数量已满，请选择要丢弃的道具。[p]';95='        在神社的庇佑下获得了『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』护符！[p]';97='        在神社的庇佑下，『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』护符落入手中！[p]';98='        但是护符持有数量已满，无法收下……[p]';107='突然出现的神秘黑影向我们袭来！[p]';129='        我等了一会儿，却什么也没有发生。[p]';130='        [emb exp="f.battleDataDic[''player''][''name'']"]一脸泄气地离开了这里。[p]'}
$maps['7']=@{17='在森林中徘徊时，我不幸遇到了『死神』。[p]';18='如果消耗魔力碎片施放扰乱魔法，或许还能勉强逃走……[p]';20='[choices_glink choicesText="消耗魔力碎片(" + f.costFragment + ")" choicesTarget="*exec"]';21='[choices_glink choicesText="向死神发起挑战" choicesTarget="*battle"]';37='施放扰乱魔法的同时，我向后方奔去。[p]';38='我拼命迈动双腿，总算成功逃离了死神。[p]';51='死神举起镰刀，向我们袭来！[p]'}
$maps['8']=@{12='在充满魔力的洞窟中，我遇到了掌管『硬币』的使魔。[p]';13='它投来好战的目光，看来无法避免战斗。[p]';14='不过，在这个空间战斗，似乎能比平时获得更多魔力碎片。[p]';21='硬币将阿尔卡那的力量寄宿于自身，向我们袭来！[p]'}
$maps['9']=@{11='穿过昏暗的道路后，前方通往一间奢华得前所未见的王座厅。[p]';12='昏暗空间中央的王座散发着微弱灯光。从那把椅子上，似乎能获得一些魔力碎片。[p]';13='然而，背后传来的沉重压迫感让我脑中浮现不祥的想象。[p]';14='触碰王座时，究竟会发生什么？[p]';16='[choices_glink choicesText="从王座获得魔力碎片（50%概率战斗）" choicesTarget="*exec"]';17='[choices_glink choicesText="什么也不做，直接离开" choicesTarget="*skip"]';33='从王座获得了[emb exp="f.getFragment"]个魔力碎片！[p]';37='    听到脚步声回头一看，压迫感的源头――『皇帝』正站在那里，堵住了退路！[p]';60='    我回头确认身后什么都没有，赶紧离开了这里。[p]';70='遵循从背后察觉危险的直觉，我没有触碰王座，离开了这里。[p]'}
$maps['10']=@{11='穿过森林继续前进后，我来到一座飘散着甜美气息的花园。[p]';12='一踏入花园，蠕动的花朵便立刻封住了退路。[p]';13='与此同时，我察觉到花园深处出现了强大的魔力。看来那里沉睡着强大的阿尔卡那之力。[p]';14='如果现在强行返回，邪恶气息的侵蚀应该能降到最低。[p]';15='可是，想获得阿尔卡那之力，就必须继续前进。[p]';17='[choices_glink choicesText="继续前进（最多获得 7 个『寄生的仇花』）" choicesTarget="*exec"]';18='[choices_glink choicesText="返回（获得 1 个『寄生的仇花』）" choicesTarget="*skip"]';38='从荆棘深处发现并获得了『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';39='作为代价，护符的空位被『[emb exp="sf.amuletConstList[22][''name'']"]』填满。[p]';54='我强行劈开挡路的花草，总算离开了这座花园。[p]'}
$maps['11']=@{14='正在前进的山路，空气突然骤变。[p]';15='周围突然充满沉重的魔力，视野仿佛开始旋转。就在下一瞬间――[p]';20='――我被无形力量的洪流击中，身体被狠狠轰飞。[p]';22='睁开眼时，景色已经恢复原状。[p]';23='但由于刚才高密度的魔力扰乱了魔术，手中的一半阿尔卡那变质成了其他阿尔卡那。[p]'}
$maps['12']=@{11='不经意睁开眼时，我正呆立在一座陌生校舍的楼梯平台。[p]';12='前后相对的是两面相互反射光芒的对照镜。[p]';13='凝视黑暗深处，阿尔卡那的纹样虽然模糊，却逐渐浮现出来。[p]';14='看来，我选中的阿尔卡那之力被复制成了另一张随机阿尔卡那。[p]';15='居住在镜底的空洞黑影，正询问我想复制哪一张阿尔卡那。[p]';49='『[emb exp="sf.familiarStatusList[f.selectArcanaNo][''name'']"]』阿尔卡那被写入了『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』的力量！[p]'}
$maps['14']=@{12='在充满神圣力量的洞窟中，我遇到了『世界』的使魔。[p]';13='世界似乎会赐予我稀有阿尔卡那、道具或护符中的一种。[p]';15='[choices_glink choicesText="收下阿尔卡那" choicesTarget="*arcana"]';16='[choices_glink choicesText="收下道具" choicesTarget="*item"]';17='[choices_glink choicesText="收下护符" choicesTarget="*amulet"]';36='在世界的恩赐下获得了『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';58='在世界的恩赐下获得了『[emb exp="sf.itemConstList[f.getItemId][''name'']"]』道具！[p]';60='    道具持有数量已满，请选择要丢弃的道具。[p]';117='    在世界的恩赐下获得了『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』护符！[p]';119='    在世界的恩赐下，『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』护符落入手中！[p]';120='    但是护符持有数量已满，无法收下……[p]'}
$maps['15']=@{13='正在前进的山路，空气突然骤变。[p]';14='低头一看，不知何时已经缠上了一颗散发着诡异暗色光芒的宝石。[p]';15='消耗阿尔卡那之力，似乎就能驱散宝石的诅咒……[p]';17='    但是没有可消耗的阿尔卡那，无法驱散诅咒。[p]';22='[choices_glink choicesText="消耗阿尔卡那驱散诅咒" choicesTarget="*arcana"]';23='[choices_glink choicesText="接受黑暗宝石" choicesTarget="*skip"]';42='    灰色框的阿尔卡那无法选择。[p]';68='消耗阿尔卡那之力，总算驱散了宝石的诅咒。[p]';69='消耗的阿尔卡那已转换为『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';96='获得了护符『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』！[p]';98='    无法承受魔力的压力，一枚护符碎裂了……[p]'}
foreach($key in $maps.Keys){$path=Join-Path $base ($key+'.ks');$lines=[System.Collections.Generic.List[string]](Get-Content $path -Encoding UTF8);foreach($n in $maps[$key].Keys){$lines[$n-1]=$maps[$key][$n]};[IO.File]::WriteAllLines($path,$lines,[Text.UTF8Encoding]::new($false))}
