$base='C:\Users\pc\Desktop\TheBlackLilyBloomsinHerEyes\chinese-patch\source\data\scenario\zh-CN\rogueLike\event'
$maps=@{}
$maps['0']=@{11='发现了魔法炼金设施。[p]';12='看来在这里投入一张阿尔卡那，就能将其转换为另一张阿尔卡那。[p]';14='[choices_glink choicesText="开始炼金" choicesTarget="*exec"]';15='[choices_glink choicesText="不炼金直接离开" choicesTarget="*skip"]';50='已转换为『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';60='决定不进行炼金，直接离开。[p]'}
$maps['1']=@{15='发现了魔法炼金设施。[p]';16='看来在这里可以消耗阿尔卡那或魔力碎片来获得道具。[p]';18='[choices_glink choicesText="消耗阿尔卡那开始炼金" choicesTarget="*execArcana"]';19='[choices_glink choicesText="消耗魔力碎片(200)开始炼金" choicesTarget="*execFragment"]';20='[choices_glink choicesText="不炼金直接离开" choicesTarget="*skip"]';27='    但是没有持有可用于炼金的阿尔卡那。[p]';28='    [emb exp="sf.playerName"]只好老实离开了那里。[p]';47='    但是没有持有足够炼金所需的魔力碎片。[p]';48='    [emb exp="sf.playerName"]只好老实离开了那里。[p]';68='    灰色框的阿尔卡那无法选择。[p]';95='消耗的阿尔卡那已转换为『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';108='获得了道具『[emb exp="sf.itemConstList[f.getItemId][''name'']"]』！[p]';110='    道具持有数量已满，请选择要丢弃的道具。[p]';139='决定不进行炼金，直接离开。[p]'}
$maps['2']=@{15='发现了魔法炼金设施。[p]';16='看来在这里可以消耗阿尔卡那或魔力碎片来获得护符。[p]';19='    但是护符持有数量已满，因此决定不进行炼金，直接离开。[p]';26='[choices_glink choicesText="消耗阿尔卡那开始炼金" choicesTarget="*execArcana"]';27='[choices_glink choicesText="消耗魔力碎片(300)开始炼金" choicesTarget="*execFragment"]';28='[choices_glink choicesText="不炼金直接离开" choicesTarget="*skip"]';35='    但是没有持有可用于炼金的阿尔卡那。[p]';36='    [emb exp="sf.playerName"]只好老实离开了那里。[p]';55='    但是没有持有足够炼金所需的魔力碎片。[p]';56='    [emb exp="sf.playerName"]只好老实离开了那里。[p]';76='    灰色框的阿尔卡那无法选择。[p]';103='消耗的阿尔卡那已转换为『[emb exp="sf.familiarStatusList[f.getArcanaNo][''name'']"]』阿尔卡那！[p]';116='获得了护符『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』！[p]';130='决定不进行炼金，直接离开。[p]'}
$maps['3']=@{14='在森林中行走时，一名可疑商人向我提出交易。[p]';15='他说，只要交出一枚护符，就会交换给我另一枚护符。[p]';17='    但我没有持有护符，于是拒绝交易，离开了那里。[p]';24='[choices_glink choicesText="交出护符" choicesTarget="*exec"]';25='[choices_glink choicesText="不交出，直接离开" choicesTarget="*skip"]';50='可疑商人把『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』护符放到我手中。[p]';51='获得了护符『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』！[p]';62='我拒绝交易，离开了那里。[p]'}
$maps['4']=@{15='深入洞窟后，我来到一处充满耀眼魔石与魔力的空间。[p]';16='挖掘部分魔石，似乎就能获得魔力碎片。不过，从充盈的魔力中也能感到不祥力量的气息。[p]';18='[choices_glink choicesText="获得魔力碎片(400)与『黑暗宝石』" choicesTarget="*exec"]';19='[choices_glink choicesText="不挖掘直接离开" choicesTarget="*skip"]';44='获得了[emb exp="f.getFragment" ]个魔力碎片！[p]';45='获得了护符『[emb exp="sf.amuletConstList[f.getAmuletId][''name'']"]』！[p]';47='    无法承受魔力的压力，一枚护符碎裂了……[p]';59='凭借察觉危险的直觉，我没有挖掘，离开了这里。[p]'}
$maps['5']=@{15='发现了魔法炼金设施。[p]';16='看来在这里投入一件道具或护符，就能转换为魔力碎片。[p]';18='    但我既没有道具也没有护符，于是决定不进行炼金，直接离开。[p]';24='[choices_glink choicesText="炼金获得魔力碎片(300)" choicesTarget="*exec"]';25='[choices_glink choicesText="不炼金直接离开" choicesTarget="*skip"]';61='获得了[emb exp="f.getFragment"]个魔力碎片！[p]';72='决定不进行炼金，直接离开。[p]'}
foreach($key in $maps.Keys){$path=Join-Path $base ($key+'.ks');$lines=[System.Collections.Generic.List[string]](Get-Content $path -Encoding UTF8);foreach($n in $maps[$key].Keys){$lines[$n-1]=$maps[$key][$n]};[IO.File]::WriteAllLines($path,$lines,[Text.UTF8Encoding]::new($false))}
